### ISSUE TITLE
App hints need to be added in for Installation, Settings and About

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-Android#166]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In Scribe-iOS there are app hints present in the Installation, Settings, and About Pages. These are used to give information about the specific page used in the app and what would be the basic functionalities present on the specific page. The issue is to add these to the Scribe-Android project for the 3 pages as mentioned above for Scribe-iOS. 

These should be present for the user on the first launch and then not on screen after the user clicks ok

Image references are given below:

| Settings       | Installation         | About         |
|-----------|-----------|-----------|
| ![Image 1](https://github.com/user-attachments/assets/2ded26c5-5256-4b95-bb45-ad02c21b7008) | ![Image 2](https://github.com/user-attachments/assets/84d0442d-7bc7-4bb9-a067-d300098b9be5) | ![Image 3](https://github.com/user-attachments/assets/6181741a-240e-470f-9fb6-bd87106ec71d) |

### Contribution

I am happy to work on this and am more than willing to help anyone solve this issue by providing more details about the functionality.

**Comment by ZayJackPrvy** [comment]
Hi @henrikth93. Sorry to bother you, but I wanted to ask if I could try working on this issue. The one I chose earlier is currently blocked, and for my university assignment, I need to solve a non-trivial task. Thanks.

**Comment by henrikth93** [comment]
> university
That is absolutely fine! I will see if I can assign you to it.

**Comment by henrikth93** [comment]
> > university
> > That is absolutely fine! I will see if I can assign you to it.

You have now been assigned! :)

**Comment by andrewtavis** [comment]
Thanks for the reassign @henrikth93, and sorry that this slipped my mind, @ZayJackPrvy. We have an internship program starting right now and there's lots to do, but we'll be able to support and review.

CC @angrezichatterbox for support on this to make sure that @ZayJackPrvy can get things finished in time :)

**Comment by ZayJackPrvy** [comment]
Hi @andrewtavis  @henrikth93 I’ve created a hint_layout.xml for displaying hints, and I’ve also implemented the hint reset functionality #167 . However, I’m facing an issue with where exactly to place the hint_layout.xml bar.

In MainFragment, I placed it on binding.root, but it covers the entire screen. In SettingsFragment, I placed it on binding.settingsHolder because I encountered an error stating that a ScrollView can only have one child. When I placed it in settingsHolder, the hint appeared at the bottom of the screen, same isssue with hint in AboutFragment. 

Could you provide some guidance on where to place the hint bar properly in these fragments? 
![image](https://github.com/user-attachments/assets/223f5182-1273-4655-97d4-8d33d4a08527)
![image](https://github.com/user-attachments/assets/4d7c4f58-b8cf-458e-8f3d-f3c0c750403c) 
![image](https://github.com/user-attachments/assets/bc260ce5-d8ab-43b8-8bea-26d7640eabf2)

**Comment by andrewtavis** [comment]
CC @angrezichatterbox for support here :) Thanks for taking this on, @ZayJackPrvy! @angrezichatterbox will know best how to solve this 😊

**Comment by angrezichatterbox** [comment]
Could you implement this in `activity_main.xml` and create a function in the main activity to enable and disable it? You can then call this function from the other fragments, similar to how the Action Bar margin is adjusted based on the current page. Its function is implemented in the main and called from other fragments. 

You could put a layout constraint for the view pager in the `activity_main.xml` to be below the hint.

**Comment by ZayJackPrvy** [comment]
@andrewtavis I didn't link #166  and #167  to the last pull request, so both of them are still open. 
I appreciate the opportunity to be a part of this project. :)

**Comment by andrewtavis** [comment]
Thanks so much for the reminder, @ZayJackPrvy! Awesome :) You're a very welcome member of this project 😊 Hope to work with you again soon!
