### ISSUE TITLE
Look into AOSP as a basis

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Android#34]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Something that was just discussed is using [AOSP’s Android keyboard](https://www.apkmirror.com/apk/lineageos/android-keyboard-aosp-2/) as a basis for Scribe-Android. Looking into this would be something we should do 😊

**Comment by andrewtavis** [comment]
I’d say that maintaining the current code base makes some sense given the app structure and such, but maybe AOSP has a convenient way of making an installable Android keyboard.

**Comment by angrezichatterbox** [comment]
Could I do any help in this issue .

**Comment by andrewtavis** [comment]
This would be an interesting thing to check out, @angrezichatterbox! Maybe you could research it a bit and we could close this it it's not possible. We can maybe do a call in a few weeks to discuss what's next? Happy to plan things out for you!

And I'll get to the current PRs eventually. Really appreciate your consistency here. After this weekend I should have a bit more time :)

**Comment by andrewtavis** [comment]
Assigned, and let me know what you find here!

**Comment by angrezichatterbox** [comment]
I am not able to install the aosp keyboard apk on my android simulator .. However I looked onto some of it features and also I checked out on the fork projects of aosp keyboard called simple keyboard which was able to install and got some similarities  between the current scribe keyboard features and simple keyboard However when I searched about aosp keyboard I got to know that it has gesture control and also word correction . However I wasn't able to test any of these features since simple keyboard didn't have it . I would continue to try to install the aosp keyboard

**Comment by andrewtavis** [comment]
Hey @angrezichatterbox 👋 Scribe-Android is based off of Simple Keyboard, so the functionality that that one has should also generally be over here. I don't think there were too many changes from Simple Keyboard from when I cloned it, and I know that that project now has license issues, but it's also a thought to see what else we could bring over from that project from before the license switched. Let's be in touch on this!

**Comment by andrewtavis** [comment]
Thanks so much for checking!

**Comment by angrezichatterbox** [comment]
Simple keyboard was quite similar to Scribe even now .  I would check if I could get aosp apk on my android simulator to check the various features it offers

**Comment by andrewtavis** [comment]
Thanks for looking into this, @angrezichatterbox!

**Comment by andrewtavis** [comment]
Hey @angrezichatterbox 👋 Do you think we're good to close this? I just checked some of the recent [commits to Simple Keyboard](https://github.com/SimpleMobileTools/Simple-Keyboard/commits/main/?before=b22666eb248d8a21c2bca06412cac91033388623+35), and I really don't think there's much we can get from there that we couldn't just make our own issues for. To me trying to reference the codebase over there at this point is likely more of a bother than something that will help.

If you think some more research for the aosp apk would help, then we can keep this open, but if we're fine with this, then happy to close so that we have an open slate for new issues 😊

**Comment by angrezichatterbox** [comment]
I have noticed some good features of AOSP keyboard but like typing using swipe gestures and auto correct. Other than these i haven't found much features because i wasn't able to use it.I hope implementing those features could be possible independently rather than using it as a basis.I am not able to use the lineage os aosp keyboard on my devices so i am not able to comment on any of its other features.

**Comment by andrewtavis** [comment]
Based on the above, I think that we can close this up 😊 Maybe we can reference how they're doing it in the future, but I think the structure of the project is fine for now for getting an MVP out. Thanks, @angrezichatterbox!
